name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:
  ubuntu-tests:
    name: Run all tests on Ubuntu
    runs-on: ubuntu-22.04 # Latest misses mono for .NET Framework
    env:
      DOWNLOAD_KEY: ${{ secrets.DOWNLOAD_KEY }}

    steps:
      - uses: actions/checkout@v4
        
      - name: Test All
        run: dotnet test -c Release

  dotnet-test:
    name: Run Integration Tests
    runs-on: windows-latest
    env:
      DOWNLOAD_KEY: ${{ secrets.DOWNLOAD_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Integration Tests
        run: dotnet test -c Release --filter TestCategory=IntegrationTest

  CICD:
    needs: [ubuntu-tests, dotnet-test]
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
    with:
      sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.Sdk
    secrets:
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}
